backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "products"
    label: "Produtos"
    folder: "content/products"
    create: true
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Preço", name: "price", widget: "number" }
      - { label: "Imagem (URL)", name: "image", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
